# Generated by Django 2.2.9 on 2020-05-11 06:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_auto_20200509_1534'),
    ]

    operations = [
        migrations.RenameField(
            model_name='payment',
            old_name='stripe_charges_id',
            new_name='stripe_charge_id',
        ),
    ]
