# Generated by Django 2.2.9 on 2020-05-21 13:54

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0019_remove_order_shipping_address'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Address',
            new_name='BillingAddress',
        ),
    ]
